# Project Information
site_name: Medicare Documentation
site_description: 'Extra Medicare Documentation'
site_author: 'Kyle Barron'

docs_dir: 'docs'
site_dir: 'site'

# Repository
repo_name: 'medicare-documentation'
repo_url: 'https://github.com/kylebarron/medicare-documentation'

# Theme
theme:
    name: 'material'
    language: 'en'
    palette:
        primary: 'orange'
        accent:  'light blue'
    font:
        text: 'Nunito Sans'
        # code: 'Roboto Mono'
        code: 'Fira Code'

extra_javascript:
    - helpers.js
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - meta
    - pymdownx.arithmatex
    - pymdownx.smartsymbols
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde
    - toc:
        permalink: true
